# CNN RSS feeds (from https://rss.cnn.com/rss/)

base_poll_seconds = 100
category = "news"
content_type = "xml"
id_prefix = "cnn"
language = "en"
provenance = "cnn"
tags = [
  "news",
]

[[feeds]]
id  = "feeds"
url = "https://edition.cnn.com/?no_redirect=true&format=rss"
