# Politico RSS feeds (from https://www.politico.com/rss/)

# POLITICO RSS feeds (extracted from "POLITICO RSS Feeds - POLITICO.mhtml")

base_poll_seconds = 1000
id_prefix = "politico"
category = "news"
provenance = "politico"
tags = [
    "news",
    "politics",
]
language = "en"
content_type = "xml"

[[feeds]]
id  = "congress"
url = "http://rss.politico.com/congress.xml"

[[feeds]]
id  = "health-care"
url = "http://rss.politico.com/healthcare.xml"

[[feeds]]
id  = "defense"
url = "http://rss.politico.com/defense.xml"

[[feeds]]
id  = "economy"
url = "http://rss.politico.com/economy.xml"

[[feeds]]
id  = "energy-and-environment"
url = "http://rss.politico.com/energy.xml"

[[feeds]]
id  = "politics"
url = "https://rss.politico.com/politics-news.xml"

[[feeds]]
id  = "playbook"
url = "http://rss.politico.com/playbook.xml"

[[feeds]]
id  = "morning-tech"
url = "http://rss.politico.com/morningtech.xml"

[[feeds]]
id  = "morning-money"
url = "http://rss.politico.com/morningmoney.xml"

[[feeds]]
id  = "politico-pulse"
url = "http://rss.politico.com/politicopulse.xml"

[[feeds]]
id  = "huddle"
url = "http://rss.politico.com/huddle.xml"

[[feeds]]
id  = "morning-energy"
url = "http://rss.politico.com/morningenergy.xml"

[[feeds]]
id  = "morning-defense"
url = "http://rss.politico.com/morningdefense.xml"

[[feeds]]
id  = "politico-influence"
url = "http://rss.politico.com/politicoinfluence.xml"

[[feeds]]
id  = "morning-score"
url = "http://rss.politico.com/morningscore.xml"

[[feeds]]
id  = "morning-transportation"
url = "http://rss.politico.com/morningtransportation.xml"

[[feeds]]
id  = "morning-education"
url = "http://rss.politico.com/morningeducation.xml"

[[feeds]]
id  = "morning-tax"
url = "http://rss.politico.com/morningtax.xml"

[[feeds]]
id  = "morning-agriculture"
url = "http://rss.politico.com/morningagriculture.xml"

[[feeds]]
id  = "morning-cybersecurity"
url = "http://rss.politico.com/morningcybersecurity.xml"

[[feeds]]
id  = "morning-shift"
url = "http://rss.politico.com/morningshift.xml"

[[feeds]]
id  = "morning-trade"
url = "http://rss.politico.com/morningtrade.xml"
