# Washington Post RSS feeds (from https://www.washingtonpost.com/discussions/2018/10/12/washington-post-feeds/)

base_poll_seconds = 1000
category = "news"
content_type = "xml"
id_prefix = "wapo"
language = "en"
provenance = "wapo"
tags = [
  "news",
]

[[feeds]]
id  = "politics"
url = "https://www.washingtonpost.com/arcio/rss/category/politics/"

[[feeds]]
id  = "politics-the-fix"
url = "https://feeds.washingtonpost.com/rss/rss_the-fix"

[[feeds]]
id  = "opinions"
url = "https://www.washingtonpost.com/arcio/rss/category/opinions/"

[[feeds]]
id  = "opinions-george-f-will"
url = "https://www.washingtonpost.com/arcio/rss/author/George%20F%20-Will/"

[[feeds]]
id  = "local"
url = "https://feeds.washingtonpost.com/rss/local"

[[feeds]]
id  = "local-capital-weather-gang"
url = "https://feeds.washingtonpost.com/rss/rss_capital-weather-gang"

[[feeds]]
id  = "local-the-optimist"
url = "https://feeds.washingtonpost.com/rss/national/inspired-life"

[[feeds]]
id  = "local-retropolis"
url = "https://www.washingtonpost.com/arcio/rss/category/history/"

[[feeds]]
id  = "sports"
url = "https://www.washingtonpost.com/arcio/rss/category/sports/"

[[feeds]]
id  = "sports-high-school-sports"
url = "https://feeds.washingtonpost.com/rss/rss_recruiting-insider"

[[feeds]]
id  = "sports-dc-sports-bog"
url = "https://feeds.washingtonpost.com/rss/rss_dc-sports-bog"

[[feeds]]
id  = "sports-maryland-terrapins"
url = "https://feeds.washingtonpost.com/rss/rss_terrapins-insider"

[[feeds]]
id  = "sports-soccer"
url = "https://feeds.washingtonpost.com/rss/rss_soccer-insider"

[[feeds]]
id  = "sports-washington-commanders"
url = "https://feeds.washingtonpost.com/rss/rss_football-insider"

[[feeds]]
id  = "sports-washington-capitals"
url = "https://feeds.washingtonpost.com/rss/rss_capitals-insider"

[[feeds]]
id  = "sports-washington-nationals"
url = "https://feeds.washingtonpost.com/rss/rss_nationals-journal"

[[feeds]]
id  = "sports-washington-wizards"
url = "https://feeds.washingtonpost.com/rss/rss_wizards-insider"

[[feeds]]
id  = "technology"
url = "https://feeds.washingtonpost.com/rss/business/technology"

[[feeds]]
id  = "national"
url = "https://feeds.washingtonpost.com/rss/national"

[[feeds]]
id  = "world"
url = "https://feeds.washingtonpost.com/rss/world"

[[feeds]]
id  = "business"
url = "https://feeds.washingtonpost.com/rss/business"

[[feeds]]
id  = "lifestyle"
url = "https://feeds.washingtonpost.com/rss/lifestyle"

[[feeds]]
id  = "entertainment"
url = "https://feeds.washingtonpost.com/rss/entertainment"

[[feeds]]
id  = "entertainment-going-out-guide"
url = "https://feeds.washingtonpost.com/rss/rss_going-out-gurus"
