# Wall Street Journal (WSJ) RSS feeds (extracted from news-and-feeds.mhtml)

base_poll_seconds = 1000
id_prefix = "wsj"
category = "news"
provenance = "wsj"
tags = [
    "news",
]
language = "en"
content_type = "xml"

[[feeds]]
id = "opinion"
url = "https://feeds.content.dowjones.io/public/rss/RSSOpinion"

[[feeds]]
id = "world-news"
url = "https://feeds.content.dowjones.io/public/rss/RSSWorldNews"

[[feeds]]
id = "u-s-business"
url = "https://feeds.content.dowjones.io/public/rss/WSJcomUSBusiness"

[[feeds]]
id = "markets-news"
url = "https://feeds.content.dowjones.io/public/rss/RSSMarketsMain"

[[feeds]]
id = "technology-whats-news"
url = "https://feeds.content.dowjones.io/public/rss/RSSWSJD"

[[feeds]]
id = "lifestyle"
url = "https://feeds.content.dowjones.io/public/rss/RSSLifestyle"

[[feeds]]
id = "u-s"
url = "https://feeds.content.dowjones.io/public/rss/RSSUSnews"

[[feeds]]
id = "politics"
url = "https://feeds.content.dowjones.io/public/rss/socialpoliticsfeed"

[[feeds]]
id = "economy"
url = "https://feeds.content.dowjones.io/public/rss/socialeconomyfeed"

[[feeds]]
id = "arts"
url = "https://feeds.content.dowjones.io/public/rss/RSSArtsCulture"

[[feeds]]
id = "real-estate"
url = "https://feeds.content.dowjones.io/public/rss/latestnewsrealestate"

[[feeds]]
id = "personal-finance"
url = "https://feeds.content.dowjones.io/public/rss/RSSPersonalFinance"

[[feeds]]
id = "health"
url = "https://feeds.content.dowjones.io/public/rss/socialhealth"

[[feeds]]
id = "style"
url = "https://feeds.content.dowjones.io/public/rss/RSSStyle"

[[feeds]]
id = "sports"
url = "https://feeds.content.dowjones.io/public/rss/rsssportsfeed"
