[formatting]
array_auto_expand = true
array_auto_collapse = false
array_trailing_comma = true
inline_table_expand = true
compact_inline_tables = false

[[rule]]
include = ["crates/fetcher/res/config.toml", "crates/fetcher/res/docker.toml"]
schema = { path = "crates/fetcher/res/schemas/config.schema.json" }

[[rule]]
include = ["crates/fetcher/res/domains.toml"]
schema = { path = "crates/fetcher/res/schemas/domains.schema.json" }

[[rule]]
include = ["crates/fetcher/res/categories.toml"]
schema = { path = "crates/fetcher/res/schemas/categories.schema.json" }

[[rule]]
include = ["crates/fetcher/res/feeds/**/global.toml"]
schema = { path = "crates/fetcher/res/schemas/global.schema.json" }

[[rule]]
include = ["crates/fetcher/res/feeds/**/*.toml"]
schema = { path = "crates/fetcher/res/schemas/feeds.schema.json" }
