[formatting]
array_auto_expand = true
array_auto_collapse = false
array_trailing_comma = true
inline_table_expand = true
compact_inline_tables = false

[[rule]]
include = ["res/config.toml", "res/docker.toml"]
schema = { path = "res/schemas/config.schema.json" }

[[rule]]
include = ["res/domains.toml"]
schema = { path = "res/schemas/domains.schema.json" }

[[rule]]
include = ["res/categories.toml"]
schema = { path = "res/schemas/categories.schema.json" }

[[rule]]
include = ["res/feeds/**/*.toml"]
schema = { path = "res/schemas/feeds.schema.json" }
