[[domains]]
name = "hnrss.org"
max_concurrent_requests = 1

[[domains]]
name = "xkcd.com"
max_concurrent_requests = 1

[[domains]]
name = "govinfo.gov"
max_concurrent_requests = 1

[[domains]]
name = "youtube.com"
max_concurrent_requests = 1

[[domains]]
name = "arxiv.org"
max_concurrent_requests = 1

[[domains]]
name = "tradingeconomics.com"
max_concurrent_requests = 1

[[domains]]
name = "bls.gov"
max_concurrent_requests = 1

[[domains]]
name = "federalregister.gov"
max_concurrent_requests = 1

[[domains]]
name = "omny.fm"
max_concurrent_requests = 1
