[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "feedrv3"
path = "src/main.rs"

[dependencies]
feedrv3-core = { path = "../core" }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.44"
