[[feeds]]
id = "podcasts-audiochuck-1322200189"
url = "https://feeds.simplecast.com/qm_9xx0g"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1603011962"
url = "https://feeds.simplecast.com/ZH32N6UM"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1532894981"
url = "https://feeds.simplecast.com/GdzgJRQH"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1535403320"
url = "https://feeds.simplecast.com/LqfhW4oK"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1500667648"
url = "https://feeds.simplecast.com/kC8PV5p6"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1483252435"
url = "https://feeds.simplecast.com/6E74sk6q"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1728272114"
url = "https://feeds.simplecast.com/q8EXDCJg"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1668474126"
url = "https://feeds.simplecast.com/sxk7RTyt"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1750724132"
url = "https://feeds.simplecast.com/EByNnoqi"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1544279344"
url = "https://feeds.simplecast.com/rHwKqPkj"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1525430395"
url = "https://feeds.simplecast.com/APPRR1zE"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1590577089"
url = "https://feeds.simplecast.com/Gg33ecoK"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1571194279"
url = "https://feeds.simplecast.com/of_GM9lR"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1713959765"
url = "https://feeds.simplecast.com/654kY38X"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1487402394"
url = "https://feeds.simplecast.com/V6PKvcd1"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1557670111"
url = "https://feeds.simplecast.com/HAWfzrHC"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1576206663"
url = "https://feeds.simplecast.com/Pgxho1td"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1640747488"
url = "https://feeds.simplecast.com/e8KuTkTk"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audiochuck-1582833356"
url = "https://feeds.simplecast.com/1AmhqQ4_"
base_poll_seconds = 1000
