[[feeds]]
id = "podcasts-economist-151230264"
url = "https://access.acast.com/rss/ec380acc-fe13-46a0-991f-a1e508d126f8"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1449631195"
url = "https://access.acast.com/rss/d556eb54-6160-4c85-95f4-47d9f5216c49"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1487173754"
url = "https://access.acast.com/rss/theeconomistmorningbriefing/default"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1785226676"
url = "https://access.acast.com/rss/672ceccb61e4ef810ff282c0/default"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-420929545"
url = "https://access.acast.com/rss/39fc4a99-8861-437d-81e2-684d13e48f92"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1494037881"
url = "https://access.acast.com/rss/57cc3c7d-b0fd-4930-9279-4e84c75df457"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-508376907"
url = "https://feeds.acast.com/public/shows/e421d786-ec36-4148-aa99-7a3b2928a779"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1651657142"
url = "https://access.acast.com/rss/633ebf6dfc7f5a0012acdc97"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-313848583"
url = "https://access.acast.com/rss/8457b14f-24d4-4f1a-a274-e6188315170b"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1705972518"
url = "https://access.acast.com/rss/64ee35bafc643000110d1607"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1642926713"
url = "https://access.acast.com/rss/62cff2d9d455860013698a7f"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1850969703"
url = "https://feeds.acast.com/public/shows/6909b7a46204e248db2b1b29"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1572322263"
url = "https://access.acast.com/rss/bb7c5a84-b3ab-4912-950b-ded7a7f6fc17"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1484868161"
url = "https://access.acast.com/rss/55ec5063-b0f7-4d0d-9d8b-7535915f3aec"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1738484939"
url = "https://access.acast.com/rss/65ef1d0f3e599300175a2a58"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1670758917"
url = "https://access.acast.com/rss/63beed437ae74e001002382f"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1108555682"
url = "https://access.acast.com/rss/4d641cbd-af7c-4475-81e8-c6a118bde4ee"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1752139463"
url = "https://access.acast.com/rss/6660d0875259600012b78f75"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1409838532"
url = "https://access.acast.com/rss/8044dc9e-e5f2-44bd-9c1c-e86bd88b72a0"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-economist-1586004652"
url = "https://access.acast.com/rss/a2466097-64ef-4550-b53b-24d082145a43"
base_poll_seconds = 1000
