[[feeds]]
id = "podcasts-nbc-1464919521"
url = "https://podcastfeeds.nbcnews.com/HL4TzgYC"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1854800589"
url = "https://feeds.simplecast.com/xZ7ozPd7"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1721921086"
url = "https://podcastfeeds.nbcnews.com/2E7hl2MC"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1837934108"
url = "https://feeds.simplecast.com/kDtzORa8"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1711415265"
url = "https://podcastfeeds.nbcnews.com/jj0_J87C"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1842552298"
url = "https://feeds.simplecast.com/NoKM4LKS"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1794421874"
url = "https://feeds.simplecast.com/TKUQ2Pih"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1634842284"
url = "https://podcastfeeds.nbcnews.com/lu6kQb_J"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1781332339"
url = "https://feeds.simplecast.com/g_JdvI7_"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1745566056"
url = "https://podcastfeeds.nbcnews.com/dateline-true-crime-weekly"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1627526461"
url = "https://podcastfeeds.nbcnews.com/Y5c_XSlq"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1479234915"
url = "https://podcastfeeds.nbcnews.com/jDT1YfkK"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1707558987"
url = "https://podcastfeeds.nbcnews.com/RPWEjhKq"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1652973017"
url = "https://podcastfeeds.nbcnews.com/iY08mEr1"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1510365500"
url = "https://podcastfeeds.nbcnews.com/q4pgd8dd"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1736208092"
url = "https://podcastfeeds.nbcnews.com/Cg8nW0Tu"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1642995848"
url = "https://podcastfeeds.nbcnews.com/0rrAyZ2Q"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1675387068"
url = "https://podcastfeeds.nbcnews.com/yiuok6R9"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1772312070"
url = "https://podcastfeeds.nbcnews.com/fPAuP5ub"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1593884827"
url = "https://podcastfeeds.nbcnews.com/SoH6_G_Z"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1561388976"
url = "https://podcastfeeds.nbcnews.com/h98PMwLp"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1540849480"
url = "https://podcastfeeds.nbcnews.com/x7rChckj"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1718562878"
url = "https://podcastfeeds.nbcnews.com/hBRFjlqK"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1463081342"
url = "https://podcastfeeds.nbcnews.com/1GllG_AQ"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-nbc-1826129003"
url = "https://feeds.simplecast.com/A1AJEBrE"
base_poll_seconds = 1000
