[[feeds]]
id = "podcasts-vox-1073226719"
url = "https://feeds.megaphone.fm/pivot"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1498802610"
url = "https://feeds.megaphone.fm/WWO6655869236"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1346207297"
url = "https://feeds.megaphone.fm/VMP5705694065"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1643307527"
url = "https://feeds.megaphone.fm/VMP1684715893"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1744631325"
url = "https://feeds.megaphone.fm/profgmarkets"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1774505095"
url = "https://feeds.megaphone.fm/VMP7229898872"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1850526014"
url = "https://feeds.megaphone.fm/VMP3740058044"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1554578197"
url = "https://feeds.megaphone.fm/VMP9331026707"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1730985049"
url = "https://feeds.megaphone.fm/daretolead"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1081584611"
url = "https://feeds.megaphone.fm/theezrakleinshow"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1494350511"
url = "https://feeds.megaphone.fm/GLT4889391284"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-430333725"
url = "https://feeds.megaphone.fm/vergecast"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-918896288"
url = "https://feeds.megaphone.fm/VMP6255701211"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1533533467"
url = "https://feeds.megaphone.fm/HOOSWTABSGLOBALLLC7896801906"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1676999261"
url = "https://feeds.megaphone.fm/VMP1282389759"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-934552872"
url = "https://feeds.megaphone.fm/switchedonpop"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1042433083"
url = "https://feeds.megaphone.fm/theweeds"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1840983742"
url = "https://feeds.megaphone.fm/VMP1872211679"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1011668648"
url = "https://feeds.megaphone.fm/recodedecode"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1203393721"
url = "https://feeds.megaphone.fm/VMP8521265258"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1510142364"
url = "https://feeds.megaphone.fm/BLU4105848842"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1812530040"
url = "https://feeds.megaphone.fm/VMP8863223339"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1080467174"
url = "https://feeds.megaphone.fm/recodemedia"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1633134223"
url = "https://feeds.megaphone.fm/VMP7932485726"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1829793986"
url = "https://feeds.megaphone.fm/VMP1222419031"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1465767420"
url = "https://feeds.megaphone.fm/landofthegiants"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1840154537"
url = "https://feeds.megaphone.fm/VMP5858892209"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1832076220"
url = "https://feeds.megaphone.fm/VMP6677258445"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1594675355"
url = "https://feeds.megaphone.fm/coverstory"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1437189814"
url = "https://feeds.megaphone.fm/thecut"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1438157174"
url = "https://feeds.megaphone.fm/futureperfect"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1585658065"
url = "https://feeds.megaphone.fm/STU4418364045"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-vox-1535242667"
url = "https://feeds.megaphone.fm/VMP3653409962"
base_poll_seconds = 1000
