base_poll_seconds = 500
category = "journals"
content_type = "xml"
id_prefix = "arxiv"
language = "en"
provenance = "arxiv"
tags = [
  "journals",
  "research",
]

[[feeds]]
id  = "econ"
url = "https://rss.arxiv.org/rss/econ"

[[feeds]]
id  = "eess"
url = "https://rss.arxiv.org/rss/eess"

[[feeds]]
id  = "stat"
url = "https://rss.arxiv.org/rss/stat"

[[feeds]]
id  = "q-fin"
url = "https://rss.arxiv.org/rss/q-fin"

[[feeds]]
id  = "q-bio"
url = "https://rss.arxiv.org/rss/q-bio"

[[feeds]]
id  = "cs"
url = "https://rss.arxiv.org/rss/cs"

[[feeds]]
id  = "quant-ph"
url = "https://rss.arxiv.org/rss/quant-ph"

[[feeds]]
id  = "physics"
url = "https://rss.arxiv.org/rss/physics"

[[feeds]]
id  = "nucl-th"
url = "https://rss.arxiv.org/rss/nucl-th"

[[feeds]]
id  = "nucl-ex"
url = "https://rss.arxiv.org/rss/nucl-ex"

[[feeds]]
id  = "nlin"
url = "https://rss.arxiv.org/rss/nlin"

[[feeds]]
id  = "math-ph"
url = "https://rss.arxiv.org/rss/math-ph"

[[feeds]]
id  = "hep-th"
url = "https://rss.arxiv.org/rss/hep-th"

[[feeds]]
id  = "hep-lat"
url = "https://rss.arxiv.org/rss/hep-lat"

[[feeds]]
id  = "hep-ex"
url = "https://rss.arxiv.org/rss/hep-ex"

[[feeds]]
id  = "gr-qc"
url = "https://rss.arxiv.org/rss/gr-qc"

[[feeds]]
id  = "cond-mat"
url = "https://rss.arxiv.org/rss/cond-mat"

[[feeds]]
id  = "astro-ph"
url = "https://rss.arxiv.org/rss/astro-ph"
