base_poll_seconds = 120
category = "tech"
content_type = "xml"
id_prefix = "hn"
language = "en"
provenance = "hn"
tags = [
  "tech",
]

[[feeds]]
id  = "frontpage"
url = "https://hnrss.org/frontpage"
