base_poll_seconds = 1800
category = "tech"
content_type = "xml"
id_prefix = "slashdot"
language = "en"
provenance = "slashdot"
tags = [
  "tech",
]

[[feeds]]
id  = "main"
url = "http://rss.slashdot.org/Slashdot/slashdotMain"
