base_poll_seconds = 180
category = "comics"
content_type = "xml"
id_prefix = "xkcd"
language = "en"
provenance = "xkcd"
tags = [
  "comics",
]

[[feeds]]
id  = "main"
url = "https://xkcd.com/rss.xml"
