[auth]
auto_login = true
password   = "admin"
username   = "admin"

[keybindings]
clear_filters         = "x"
entries_next          = "n"
entries_prev          = "p"
feeds_next            = "]"
feeds_prev            = "["
folder_assign         = "A"
folder_create         = "C"
folder_delete         = "X"
folder_rename         = "R"
folder_unassign       = "U"
go_bottom             = "G"
go_middle             = "M"
go_top                = "g"
move_down             = "j"
move_up               = "k"
next_tab              = "right"
open_all_entries      = "E"
open_category_menu    = "c"
open_entries          = "e"
open_search           = "/"
open_sort_menu        = "o"
open_tag_menu         = "t"
prev_tab              = "left"
quit                  = "q"
refresh               = "r"
tab_entries           = "2"
tab_favorites         = "3"
tab_feeds             = "1"
tab_folders           = "4"
tab_subscriptions     = "5"
toggle_entries_filter = "w"
toggle_favorite       = "f"
toggle_hide_empty     = "z"
toggle_hide_read      = "u"
toggle_read           = "m"
toggle_subscribe      = "s"

[server]
timeout_ms = 5000
url        = "http://localhost:8091"

[ui]
entries_page_size       = 50
favorites_page_size     = 50
feeds_page_size         = 50
folders_page_size       = 50
hide_empty_feeds        = false
hide_read_feeds         = false
refresh_interval_ms     = 500
subscriptions_page_size = 50
