base_poll_seconds = 720
category = "gov"
content_type = "xml"
id_prefix = "fed"
language = "en"
provenance = "federalreserve"
tags = [
  "economy",
  "gov",
]

[[feeds]]
id  = "clp"
url = "https://www.federalreserve.gov/feeds/clp.xml"

[[feeds]]
id  = "boardmeetings"
url = "https://www.federalreserve.gov/feeds/boardmeetings.xml"

[[feeds]]
id  = "reportforms-rss"
url = "https://www.federalreserve.gov/feeds/reportforms-rss.xml"

[[feeds]]
id  = "datadownload"
url = "https://www.federalreserve.gov/feeds/datadownload.xml"

[[feeds]]
id  = "h8"
url = "https://www.federalreserve.gov/feeds/h8.xml"

[[feeds]]
id  = "chgdel"
url = "https://www.federalreserve.gov/feeds/chgdel.xml"

[[feeds]]
id  = "cp"
url = "https://www.federalreserve.gov/feeds/cp.xml"

[[feeds]]
id  = "g19"
url = "https://www.federalreserve.gov/feeds/g19.xml"

[[feeds]]
id  = "h41"
url = "https://www.federalreserve.gov/feeds/h41.xml"

[[feeds]]
id  = "g20"
url = "https://www.federalreserve.gov/feeds/g20.xml"

[[feeds]]
id  = "for"
url = "https://www.federalreserve.gov/feeds/for.xml"

[[feeds]]
id  = "z1"
url = "https://www.federalreserve.gov/feeds/z1.xml"

[[feeds]]
id  = "fofguide"
url = "https://www.federalreserve.gov/feeds/fofguide.xml"

[[feeds]]
id  = "h10"
url = "https://www.federalreserve.gov/feeds/h10.xml"

[[feeds]]
id  = "g17"
url = "https://www.federalreserve.gov/feeds/g17.xml"

[[feeds]]
id  = "prates"
url = "https://www.federalreserve.gov/feeds/prates.xml"

[[feeds]]
id  = "h15"
url = "https://www.federalreserve.gov/feeds/h15.xml"

[[feeds]]
id  = "scoos"
url = "https://www.federalreserve.gov/feeds/scoos.xml"

[[feeds]]
id  = "sloos"
url = "https://www.federalreserve.gov/feeds/sloos.xml"

[[feeds]]
id  = "e2"
url = "https://www.federalreserve.gov/feeds/e2.xml"
