base_poll_seconds = 600
category = "gov"
content_type = "xml"
id_prefix = "sec"
language = "en"
provenance = "sec"
tags = [
  "gov",
]

[[feeds]]
id  = "press-releases"
url = "https://www.sec.gov/news/pressreleases.rss"

[[feeds]]
id  = "speeches-and-statements"
url = "https://www.sec.gov/news/speeches-statements.rss"

[[feeds]]
id  = "testimony"
url = "https://www.sec.gov/news/testimony.rss"

[[feeds]]
id  = "statements"
url = "https://www.sec.gov/news/statements.rss"

[[feeds]]
id  = "litigation"
url = "https://www.sec.gov/enforcement-litigation/litigation-releases/rss"

[[feeds]]
id  = "administrative-proceedings"
url = "https://www.sec.gov/enforcement-litigation/administrative-proceedings/rss"

[[feeds]]
id  = "trading-suspensions"
url = "https://www.sec.gov/enforcement-litigation/trading-suspensions/rss"

[[feeds]]
base_poll_seconds = 400
id                = "latest-filings"
url               = "https://www.sec.gov/cgi-bin/browse-edgar?action=getcurrent&CIK=&type=&company=&dateb=&owner=include&start=0&count=40&output=atom"
