[package]
edition = "2024"
name    = "fetcher"
version = "0.1.0"

[[bin]]
name = "feedrv3"
path = "src/main.rs"

[dependencies]
feedrv3-core = { path = "../core" }
tokio = { features = [
  "macros",
  "rt-multi-thread",
], version = "1.49.0" }
tracing = "0.1.44"
