[[feeds]]
id = "podcasts-audacity-1846701533"
url = "https://feeds.megaphone.fm/unpaused"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1480311435"
url = "https://feeds.megaphone.fm/office-ladies"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1603639502"
url = "https://feeds.megaphone.fm/fly-on-the-wall"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1291579828"
url = "https://feeds.megaphone.fm/NSR6392631259"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1506436093"
url = "https://feeds.megaphone.fm/tcb"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1811878340"
url = "https://feeds.megaphone.fm/emma-grede"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1793999230"
url = "https://feeds.megaphone.fm/hwmym"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1529346075"
url = "https://feeds.megaphone.fm/hell-high-water"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1761190671"
url = "https://feeds.megaphone.fm/heedthecall"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-431167790"
url = "https://feeds.megaphone.fm/jill-on-money"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1466851347"
url = "https://feeds.megaphone.fm/WWO7970459882"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1352546554"
url = "https://feeds.megaphone.fm/goop-podcast"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1627097720"
url = "https://feeds.megaphone.fm/rico-brogna"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1592823205"
url = "https://feeds.megaphone.fm/gone-south"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1576266622"
url = "https://feeds.megaphone.fm/hwigi"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1806711479"
url = "https://feeds.megaphone.fm/what-we-spend"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1586269186"
url = "https://feeds.megaphone.fm/powers-that-be"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1788381175"
url = "https://feeds.megaphone.fm/severance-ben-adam"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1549903604"
url = "https://feeds.megaphone.fm/unsolved-mysteries"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1741589082"
url = "https://feeds.megaphone.fm/fashion-people"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1840228484"
url = "https://feeds.megaphone.fm/nancy-cartwright"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1477610450"
url = "https://feeds.megaphone.fm/ENTDM6870186862"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-952449164"
url = "https://feeds.megaphone.fm/ENTDM8818453953"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1829499340"
url = "https://feeds.megaphone.fm/the-c-word"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1526581627"
url = "https://feeds.megaphone.fm/relative-unknown"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1595716948"
url = "https://feeds.megaphone.fm/draymond-green"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1219728105"
url = "https://feeds.megaphone.fm/yoga-girl"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1301767428"
url = "https://feeds.megaphone.fm/ENTDM4274283917"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1842883739"
url = "https://feeds.megaphone.fm/undomesticated"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1775515432"
url = "https://feeds.megaphone.fm/grill-room"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1762692129"
url = "https://feeds.megaphone.fm/the-varsity"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1366264191"
url = "https://feeds.megaphone.fm/sports-media-deitsch"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1624739131"
url = "https://feeds.megaphone.fm/gameday-in-buffalo"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1631178784"
url = "https://feeds.megaphone.fm/love-of-the-star"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1651632213"
url = "https://feeds.megaphone.fm/baseball-isnt-boring"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1460320573"
url = "https://feeds.megaphone.fm/gangster-capitalism"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1643228107"
url = "https://feeds.megaphone.fm/kickoff-with-boomer-and-valenti"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1521731236"
url = "https://feeds.megaphone.fm/in-the-valley"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1507276251"
url = "https://feeds.megaphone.fm/hope-through-history"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1212715122"
url = "https://feeds.megaphone.fm/CAD8479412636"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1849212536"
url = "https://feeds.megaphone.fm/von-miller"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1527280716"
url = "https://feeds.megaphone.fm/it-was-said"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1636534576"
url = "https://feeds.megaphone.fm/the-sunshine-place"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1691539676"
url = "https://feeds.megaphone.fm/the-set"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1804401177"
url = "https://feeds.megaphone.fm/rulebreakers-saraya"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1635420001"
url = "https://rss.amperwave.net/v2/feed/podcorn/e464c1b3c52e16a7b77894686c2b44fdaa"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1650460136"
url = "https://feeds.megaphone.fm/best-football-show"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1709963682"
url = "https://feeds.megaphone.fm/puck-putin"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1681606343"
url = "https://feeds.megaphone.fm/queens-of-the-court"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1334778747"
url = "https://feeds.megaphone.fm/skate-podcast"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1642525489"
url = "https://feeds.megaphone.fm/wolves-among-us"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1483798832"
url = "https://feeds.megaphone.fm/spits-and-suds"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-386002669"
url = "https://feeds.megaphone.fm/wfandaily"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1738048424"
url = "https://feeds.megaphone.fm/mtv"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1563421928"
url = "https://feeds.megaphone.fm/fate-of-fact"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1596530271"
url = "https://feeds.megaphone.fm/ghostwriter"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1479120204"
url = "https://feeds.megaphone.fm/lmtr"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1266445999"
url = "https://feeds.megaphone.fm/origins-jam"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1622836811"
url = "https://feeds.megaphone.fm/bustin-out-baseball"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1531522658"
url = "https://feeds.megaphone.fm/the-edge"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1570685298"
url = "https://feeds.megaphone.fm/no-place-like-home"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1625313174"
url = "https://feeds.megaphone.fm/history-is-us"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1589777606"
url = "https://feeds.megaphone.fm/treat"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1626162594"
url = "https://feeds.simplecast.com/N8L_zL3Q"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1617076670"
url = "https://feeds.megaphone.fm/fof-2"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1530292222"
url = "https://feeds.megaphone.fm/whirlwind"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1642587453"
url = "https://feeds.megaphone.fm/first-and-pod"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1711278966"
url = "https://feeds.megaphone.fm/south-philly-sauce"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1583582515"
url = "https://feeds.megaphone.fm/it-was-said-sports"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1728742759"
url = "https://feeds.megaphone.fm/one-handshake-away"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1620050867"
url = "https://feeds.megaphone.fm/garlic-fries-and-baseball-guys"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1656135611"
url = "https://rss.amperwave.net/v2/feed/audacy/d478777ac2960e9320db7e399d52319d"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1617139805"
url = "https://feeds.megaphone.fm/beat-the-streak-daily"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1700703533"
url = "https://feeds.megaphone.fm/glitter-might"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-audacity-1654739637"
url = "https://feeds.megaphone.fm/htown-hoops"
base_poll_seconds = 1000
