[[feeds]]
id = "podcasts-bbc-135067274"
url = "https://podcasts.files.bbci.co.uk/p02nq0gn.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1704480561"
url = "https://podcasts.files.bbci.co.uk/w13xtvs0.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-73330895"
url = "https://podcasts.files.bbci.co.uk/b006qykl.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1479973402"
url = "https://podcasts.files.bbci.co.uk/p07mdbhg.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-356157099"
url = "https://podcasts.files.bbci.co.uk/p002vsnk.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1524778767"
url = "https://podcasts.files.bbci.co.uk/p08llv8n.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-343580439"
url = "https://podcasts.files.bbci.co.uk/b00snr0w.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1715473158"
url = "https://podcasts.files.bbci.co.uk/w13xtvsd.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1589938734"
url = "https://podcasts.files.bbci.co.uk/m0010x7c.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1745306259"
url = "https://podcasts.files.bbci.co.uk/m001z66c.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1473150244"
url = "https://podcasts.files.bbci.co.uk/p07h19zz.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1561990291"
url = "https://podcasts.files.bbci.co.uk/w13xtvg9.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-267300884"
url = "https://podcasts.files.bbci.co.uk/p02nrss1.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-265307784"
url = "https://podcasts.files.bbci.co.uk/p02pc9pj.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1084340508"
url = "https://podcasts.files.bbci.co.uk/b07dx75g.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1689369106"
url = "https://podcasts.files.bbci.co.uk/m001mcbp.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-261291929"
url = "https://podcasts.files.bbci.co.uk/p02nrsln.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1793748839"
url = "https://podcasts.files.bbci.co.uk/p0klkdww.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-292651411"
url = "https://podcasts.files.bbci.co.uk/p02tb8vq.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1620155570"
url = "https://podcasts.files.bbci.co.uk/m0016pq3.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1741328387"
url = "https://podcasts.files.bbci.co.uk/m0000nfh.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-339986758"
url = "https://podcasts.files.bbci.co.uk/p004t1hd.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1701585239"
url = "https://podcasts.files.bbci.co.uk/p0g7xj36.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1459657136"
url = "https://podcasts.files.bbci.co.uk/w13xttx2.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1465290044"
url = "https://podcasts.files.bbci.co.uk/m0005fdz.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-130520763"
url = "https://podcasts.files.bbci.co.uk/p02nrsjn.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1540251892"
url = "https://podcasts.files.bbci.co.uk/p08yblkf.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-261786876"
url = "https://podcasts.files.bbci.co.uk/p002vsxs.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-670199157"
url = "https://podcasts.files.bbci.co.uk/b036f7w2.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1744545000"
url = "https://podcasts.files.bbci.co.uk/p0hvvqqr.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1234185718"
url = "https://podcasts.files.bbci.co.uk/p05299nl.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1683405079"
url = "https://podcasts.files.bbci.co.uk/p0fhzh45.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1735016800"
url = "https://podcasts.files.bbci.co.uk/p0hhgmp6.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-263570559"
url = "https://podcasts.files.bbci.co.uk/p02nrtyw.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1356142765"
url = "https://podcasts.files.bbci.co.uk/p0605sx6.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1819480664"
url = "https://podcasts.files.bbci.co.uk/p0lgrwds.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-351096296"
url = "https://podcasts.files.bbci.co.uk/b00nrtd2.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1592984136"
url = "https://podcasts.files.bbci.co.uk/m0011cpr.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-932499233"
url = "https://podcasts.files.bbci.co.uk/p029399x.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-342927791"
url = "https://podcasts.files.bbci.co.uk/b006qnx3.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1480370173"
url = "https://podcasts.files.bbci.co.uk/p07nkd84.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-469912037"
url = "https://podcasts.files.bbci.co.uk/b015sqc7.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1436036246"
url = "https://podcasts.files.bbci.co.uk/p07915kd.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1758749165"
url = "https://podcasts.files.bbci.co.uk/m0021j2v.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-73331209"
url = "https://podcasts.files.bbci.co.uk/p02nrtpm.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1197440162"
url = "https://podcasts.files.bbci.co.uk/p04q5p2n.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1756109243"
url = "https://podcasts.files.bbci.co.uk/m00199xy.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1601195264"
url = "https://podcasts.files.bbci.co.uk/m001324r.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1714615567"
url = "https://podcasts.files.bbci.co.uk/p0gq38lc.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1781636710"
url = "https://podcasts.files.bbci.co.uk/p0k61syt.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1690561703"
url = "https://podcasts.files.bbci.co.uk/m001mssm.rss"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-bbc-1570414193"
url = "https://podcasts.files.bbci.co.uk/p09k7ctp.rss"
base_poll_seconds = 1000
