[[feeds]]
id = "podcasts-stack-1670705840"
url = "https://feeds.acast.com/public/shows/63e24225436c36001119fc66"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-254078311"
url = "https://feeds.acast.com/public/shows/8af0c347-5e6e-48e2-8fae-3f4e765c84ab"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1338558972"
url = "https://feeds.acast.com/public/shows/4d1eb966-6f07-4562-b9f1-9fd512f9631e"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1699067317"
url = "https://feeds.acast.com/public/shows/64be9eec0ea5360011fa0255"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1243452578"
url = "https://feeds.acast.com/public/shows/c13dca0f-7a37-41c4-a043-f92b2bf6bdd1"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1335795111"
url = "https://feeds.acast.com/public/shows/fba44d70-2a73-44d9-8bf9-726e9fcc2b3e"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1718750386"
url = "https://feeds.acast.com/public/shows/64c13018dc471e0011153d21"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1768760753"
url = "https://feeds.acast.com/public/shows/66e585cfeb96eb5d24392247"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1428145927"
url = "https://feeds.acast.com/public/shows/ea096490-cf33-4a82-9a91-4c1ced1c193c"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1654508940"
url = "https://feeds.acast.com/public/shows/636e7bacdc1ddc00117a5272"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1723841408"
url = "https://feeds.acast.com/public/shows/6585f23688f900001625890c"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1272100668"
url = "https://feeds.acast.com/public/shows/1bbb3668-2a5c-4a5a-a03a-ef32dd591920"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1473436479"
url = "https://feeds.acast.com/public/shows/be0e4291-93a6-4859-ac8f-4e789c5e61cc"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1721136144"
url = "https://feeds.acast.com/public/shows/63daa946f6391d00115e5987"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1629929430"
url = "https://access.acast.com/rss/62a3443c711c070014263afb/"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1531501584"
url = "https://feeds.acast.com/public/shows/64b0c953-9171-4a84-b673-e0ef357d837a"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1588766832"
url = "https://feeds.acast.com/public/shows/8ac891c6-1401-4935-8716-a61d75399689"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1552726054"
url = "https://feeds.acast.com/public/shows/078fbdb8-908e-49aa-94c7-47bb118acead"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1620586699"
url = "https://feeds.acast.com/public/shows/625fd9fc864780001226740d"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1338557108"
url = "https://rss.acast.com/thewindsorknot"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1612482633"
url = "https://feeds.acast.com/public/shows/621f75408543f800136173b0"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1610130788"
url = "https://feeds.acast.com/public/shows/62053b0f48005b00123c463e"
base_poll_seconds = 1000

[[feeds]]
id = "podcasts-stack-1721135741"
url = "https://feeds.acast.com/public/shows/630791d68dedfe0012100306"
base_poll_seconds = 1000
