# psychicpebbles

[[feeds]]
base_poll_seconds = 500
id                = "UC--BMyA2X4a9PGAo3lTuopg"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC--BMyA2X4a9PGAo3lTuopg"

# Gaelic Neoreactionary

[[feeds]]
base_poll_seconds = 500
id                = "UC--Ru-Cve1fxhZ8m8xXxeUg"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC--Ru-Cve1fxhZ8m8xXxeUg"

# Deep Look

[[feeds]]
base_poll_seconds = 500
id                = "UC-3SbfTPJsL8fJAPKiVqBLg"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-3SbfTPJsL8fJAPKiVqBLg"

# Astrum

[[feeds]]
base_poll_seconds = 500
id                = "UC-9b7aDP6ZN0coj9-xFnrtw"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-9b7aDP6ZN0coj9-xFnrtw"

# Frostbreak

[[feeds]]
base_poll_seconds = 500
id                = "UC-Bww5W52E1FFgU89TPxBVA"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-Bww5W52E1FFgU89TPxBVA"

# M. Laser History

[[feeds]]
base_poll_seconds = 500
id                = "UC-JWw2juO3Ikj5C9VsNoGIw"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-JWw2juO3Ikj5C9VsNoGIw"

# SubAnima

[[feeds]]
base_poll_seconds = 500
id                = "UC-Jj_eFkIwnA5m75ral8_HQ"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-Jj_eFkIwnA5m75ral8_HQ"

# Hidden Machine

[[feeds]]
base_poll_seconds = 500
id                = "UC-KxYWLV-u3-rE8-_k16dUQ"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-KxYWLV-u3-rE8-_k16dUQ"

# Palu n' Sora

[[feeds]]
base_poll_seconds = 500
id                = "UC-L2KtiGCmf4l6Y_WeA2Zdg"
url               = "https://www.youtube.com/feeds/videos.xml?channel_id=UC-L2KtiGCmf4l6Y_WeA2Zdg"
