[app]
mode = "dev"
timezone = "America/Mexico_City"

[http]
host = "0.0.0.0"
port = 8091

[database]
dialect = "postgres"

[sqlite]
path = "res/db/server.sqlite"

[postgres]
host = "localhost"
port = 5432
database = "data"
user = "admin"
password = "admin"
ssl_mode = "disable"
schema = "server"

[logging]
level = "info"

[dev]
reset_on_start = true
