[[categories]]
domains = [
  "www.youtube.com",
  "youtu.be",
  "youtube.com",
]
name = "youtube"

[[categories]]
domains = [
  "bls.gov",
  "federalregister.gov",
  "govinfo.gov",
  "sec.gov",
  "www.bls.gov",
  "www.federalreserve.gov",
  "www.govinfo.gov",
  "www.sec.gov",
]
name = "gov"

[[categories]]
domains = [
  "arxiv.org",
  "rss.arxiv.org",
]
name = "journals"

[[categories]]
domains = [
  "xkcd.com",
]
name = "comics"

[[categories]]
domains = [
  "feeds.arstechnica.com",
  "hnrss.org",
  "rss.slashdot.org",
]
name = "tech"

[[categories]]
domains = [
  "cointelegraph.com",
  "feeds.bloomberg.com",
  "ir.thomsonreuters.com",
  "seekingalpha.com",
  "www.coindesk.com",
]
name = "finance"

[[categories]]
domains = [
  "edition.cnn.com",
  "feeds.content.dowjones.io",
  "feeds.washingtonpost.com",
  "rss.nytimes.com",
  "rss.politico.com",
  "www.nytimes.com",
  "www.washingtonpost.com",
]
name = "news"

[[categories]]
domains = [
  "access.acast.com",
  "anchor.fm",
  "audioboom.com",
  "feed.cdnstream1.com",
  "feed.podbean.com",
  "feeds.acast.com",
  "feeds.megaphone.fm",
  "feeds.npr.org",
  "feeds.redcircle.com",
  "feeds.simplecast.com",
  "omny.fm",
  "omnycontent.com",
  "podcastfeeds.nbcnews.com",
  "podcasts.files.bbci.co.uk",
  "publicfeeds.net",
  "rss.acast.com",
  "rss.amperwave.net",
  "rss.art19.com",
  "rss.libsyn.com",
  "subscribe.acast.com",
  "wondery.com",
  "www.omny.fm",
  "www.omnycontent.com",
  "www.spreaker.com",
  "www.theguardian.com",
]
name = "podcasts"
