[[domains]]
max_concurrent_requests = 1
name                    = "hnrss.org"

[[domains]]
max_concurrent_requests = 1
name                    = "xkcd.com"

[[domains]]
max_concurrent_requests = 1
name                    = "govinfo.gov"

[[domains]]
max_concurrent_requests = 1
name                    = "youtube.com"

[[domains]]
max_concurrent_requests = 1
name                    = "arxiv.org"

[[domains]]
max_concurrent_requests = 1
name                    = "bls.gov"

[[domains]]
max_concurrent_requests = 1
name                    = "federalregister.gov"

[[domains]]
max_concurrent_requests = 1
name                    = "omny.fm"
