base_poll_seconds = 1000
category = "podcasts"
content_type = "xml"
id_prefix = "becauselanguage"
language = "en"
provenance = "becauselanguage"
tags = [
  "podcasts",
]

[[feeds]]
id  = "main"
url = "https://rss.libsyn.com/shows/142466/destinations/897956.xml"
