# Odd Lots

base_poll_seconds = 1000
category = "podcasts"
content_type = "xml"
id_prefix = "bloomberg"
language = "en"
provenance = "bloomberg"
tags = [
  "podcasts",
]

[[feeds]]
id  = "odd-lots"
url = "https://omny.fm/shows/odd-lots/playlists/podcast.rss"

# Daybreak

[[feeds]]
id  = "daybreak"
url = "https://omny.fm/shows/bloomberg-daybreak/playlists/podcast.rss"

# Surveillance

[[feeds]]
id  = "surveillance"
url = "https://omny.fm/shows/bloomberg-surveillance/playlists/podcast.rss"

# Masters in Business

[[feeds]]
id  = "masters-in-business"
url = "https://omny.fm/shows/masters-in-business/playlists/podcast.rss"

# Big Take

[[feeds]]
id  = "big-take"
url = "https://omny.fm/shows/the-big-take/playlists/podcast.rss"

# Disclosure

[[feeds]]
id  = "disclosure"
url = "https://omny.fm/shows/disclosure/playlists/podcast.rss"

# Money Stuff

[[feeds]]
id  = "money-stuff"
url = "https://omny.fm/shows/money-stuff-the-podcast/playlists/podcast.rss"

# Bloomberg Intelligence

[[feeds]]
id  = "intelligence"
url = "https://omny.fm/shows/the-tape/playlists/podcast.rss"

# News Now

[[feeds]]
id  = "news-now"
url = "https://omny.fm/shows/bloomberg-news-now/playlists/podcast.rss"

# Bloomberg Businessweek Daily

[[feeds]]
id  = "businessweek-daily"
url = "https://omny.fm/shows/bloomberg-businessweek/playlists/podcast.rss"

# Bloomberg Tech

[[feeds]]
id  = "tech"
url = "https://omny.fm/shows/bloomberg-tech/playlists/podcast.rss"

# Merryn Talks Money

[[feeds]]
id  = "merryn-talks-money"
url = "https://omny.fm/shows/merryn-talks-money/playlists/podcast.rss"

# Bloomberg Law

[[feeds]]
id  = "law"
url = "https://omny.fm/shows/bloomberg-law/playlists/podcast.rss"

# Bloomberg Wall Street Week

[[feeds]]
id  = "wall-street-week"
url = "https://omny.fm/shows/wall-street-week/playlists/podcast.rss"

# Trumponomics

[[feeds]]
id  = "trumponomics"
url = "https://omny.fm/shows/stephanomics/playlists/podcast.rss"

# Zero: The Climate Race

[[feeds]]
id  = "zero-the-climate-race"
url = "https://omny.fm/shows/zero/playlists/podcast.rss"

# Everybody's Business

[[feeds]]
id  = "everybodys-business"
url = "https://omny.fm/shows/bloomberg-businessweek/playlists/podcast.rss"

# Trillions

[[feeds]]
id  = "trillions"
url = "https://omny.fm/shows/trillions/playlists/podcast.rss"

# Here's Why

[[feeds]]
id  = "heres-why"
url = "https://omny.fm/shows/here-is-why/playlists/podcast.rss"

# Bloomberg Business of Sports

[[feeds]]
id  = "business-of-sports"
url = "https://omny.fm/shows/bloomberg-business-of-sports/playlists/podcast.rss"

# The Deal with Alex Rodriguez and Jason Kelly

[[feeds]]
id  = "the-deal-with-alex-rodriguez-and-jason-kelly"
url = "https://omny.fm/shows/the-deal-with-alex-rodriguez-and-jason-kelly/playlists/podcast.rss"

# Balance of Power

[[feeds]]
id  = "balance-of-power"
url = "https://omny.fm/shows/balance-of-power/playlists/podcast.rss"

# Bloomberg Talks

[[feeds]]
id  = "bloomberg-talks"
url = "https://omny.fm/shows/bloomberg-talks/playlists/podcast.rss"

# Bloomberg Daybreak: Europe Edition

[[feeds]]
id  = "daybreak-europe-edition"
url = "https://omny.fm/shows/bloomberg-daybreak-europe/playlists/podcast.rss"

# Switched On

[[feeds]]
id  = "switched-on"
url = "https://omny.fm/shows/switched-on-1/playlists/podcast.rss"

# Bloomberg Daybreak: Asia

[[feeds]]
id  = "daybreak-asia"
url = "https://omny.fm/shows/bloomberg-daybreak-asia/playlists/podcast.rss"

# Big Take Asia

[[feeds]]
id  = "big-take-asia"
url = "https://omny.fm/shows/big-take-asia/playlists/big-take-asia.rss"

# Next Africa

[[feeds]]
id  = "next-africa"
url = "https://omny.fm/shows/next-africa/playlists/podcast.rss"

# Bloomberg Daybreak Am√©rica Latina

[[feeds]]
id  = "daybreak-america-latina"
url = "https://omny.fm/shows/bloomberg-daybreak-am-rica-latina/playlists/podcast.rss"

# Bloomberg Crypto

[[feeds]]
id  = "crypto"
url = "https://omny.fm/shows/bloomberg-crypto/playlists/podcast.rss"

# Listen to the Story

[[feeds]]
id  = "listen-to-the-story"
url = "https://omny.fm/shows/listen-to-the-story/playlists/podcast.rss"

# What Goes Up

[[feeds]]
id  = "what-goes-up"
url = "https://omny.fm/shows/what-goes-up/playlists/podcast.rss"

# In The City

[[feeds]]
id  = "in-the-city"
url = "https://omny.fm/shows/in-the-city/playlists/podcast.rss"

# Bloomberg Daybreak: Brasil

[[feeds]]
id  = "daybreak-brasil"
url = "https://omny.fm/shows/bloomberg-daybreak-brasil/playlists/podcast.rss"
