# Exchanges

base_poll_seconds = 1000
category = "podcasts"
content_type = "xml"
id_prefix = "goldmansachs"
language = "en"
provenance = "goldmansachs"
tags = [
  "podcasts",
]

[[feeds]]
id  = "exchanges"
url = "https://feeds.megaphone.fm/GLD9218176758"

# The Markets

[[feeds]]
id  = "the-markets"
url = "https://feeds.megaphone.fm/GLD9322922848"

#  Talks at GS

[[feeds]]
id  = "talks-at-gs"
url = "https://feeds.megaphone.fm/GLD3069230077"
