base_poll_seconds = 1000
category = "podcasts"
content_type = "xml"
id_prefix = "wondery"
language = "en"
provenance = "wondery"
tags = [
  "podcasts",
]

[[feeds]]
id  = "1345682353"
url = "https://rss.art19.com/armchair-expert"

[[feeds]]
id  = "1643745036"
url = "https://rss.art19.com/new-heights"

[[feeds]]
id  = "498130432"
url = "https://rss.art19.com/watch-what-crappens-wondery"

[[feeds]]
id  = "1313596069"
url = "https://rss.art19.com/american-history-tellers"

[[feeds]]
id  = "1435516849"
url = "https://rss.art19.com/american-scandal"

[[feeds]]
id  = "497227384"
url = "https://rss.art19.com/this-is-actually-happening-podcast"

[[feeds]]
id  = "1150510297"
url = "https://rss.art19.com/how-i-built-this"

[[feeds]]
id  = "1616682405"
url = "https://rss.art19.com/scamfluencers"

[[feeds]]
id  = "1250599915"
url = "https://rss.art19.com/redhanded"

[[feeds]]
id  = "1553335461"
url = "https://rss.art19.com/against-the-odds"

[[feeds]]
id  = "541481026"
url = "https://rss.art19.com/generation-why-podcast"

[[feeds]]
id  = "1839296232"
url = "https://rss.art19.com/not-a-very-good-murderer"

[[feeds]]
id  = "1709741912"
url = "https://rss.art19.com/mrballens-medical-mysteries"

[[feeds]]
id  = "1081124929"
url = "https://rss.art19.com/the-vanished-podcast-wondery"

[[feeds]]
id  = "1335814741"
url = "https://rss.art19.com/business-wars"

[[feeds]]
id  = "1728948939"
url = "https://rss.art19.com/the-spy-who"

[[feeds]]
id  = "1573961841"
url = "https://rss.art19.com/killer-psyche"

[[feeds]]
id  = "1710419203"
url = "https://rss.art19.com/tis-the-grinch-holiday-talk-show"

[[feeds]]
id  = "1354195914"
url = "https://rss.libsyn.com/shows/588550/destinations/5110210.xml"

[[feeds]]
id  = "1386234384"
url = "https://rss.art19.com/the-best-one-yet"

[[feeds]]
id  = "1441595858"
url = "https://www.omnycontent.com/d/playlist/796469f9-ea34-46a2-8776-ad0f015d6beb/53d07eea-d3e1-45be-a976-b2dd01039d66/e98d4757-031f-4c16-a870-b2dd01039d78/podcast.rss"

[[feeds]]
id  = "1563775446"
url = "https://rss.art19.com/british-scandal"

[[feeds]]
id  = "1791132317"
url = "https://rss.art19.com/reclaiming"

[[feeds]]
id  = "1257202425"
url = "https://rss.art19.com/tides-of-history"

[[feeds]]
id  = "1668446854"
url = "https://rss.art19.com/baby-this-is-keke-palmer"

[[feeds]]
id  = "1421573955"
url = "https://rss.art19.com/dr-death"

[[feeds]]
id  = "1771047001"
url = "https://rss.art19.com/redacted-declassified-mysteries"

[[feeds]]
id  = "1736431000"
url = "https://rss.art19.com/mind-the-game"

[[feeds]]
id  = "1447892344"
url = "https://rss.art19.com/over-my-dead-body"

[[feeds]]
id  = "1843882980"
url = "https://rss.art19.com/dear-cousin"

[[feeds]]
id  = "1620223164"
url = "https://rss.art19.com/law-crime-sidebar"

[[feeds]]
id  = "1817383627"
url = "https://rss.art19.com/flesh-and-code"

[[feeds]]
id  = "1708635466"
url = "https://rss.art19.com/ghost-story"

[[feeds]]
id  = "1848382288"
url = "https://rss.art19.com/blood-will-tell"

[[feeds]]
id  = "1495392900"
url = "https://rss.art19.com/dying-for-sex"

[[feeds]]
id  = "1459899275"
url = "https://rss.art19.com/the-shrink-next-door"

[[feeds]]
id  = "1815337795"
url = "https://rss.art19.com/liberty-lost"

[[feeds]]
id  = "1518839824"
url = "https://rss.art19.com/guru"

[[feeds]]
id  = "1707865430"
url = "https://rss.art19.com/even-the-royals"

[[feeds]]
id  = "1525281746"
url = "https://rss.art19.com/the-old-man-and-the-three"

[[feeds]]
id  = "1823990053"
url = "https://www.omnycontent.com/d/playlist/b311df04-68cc-4cd1-8a23-b1ff0112faff/b95d6196-09eb-4c59-ad54-b35d01044647/46f1267b-54fc-4321-b876-b35d01044654/podcast.rss"

[[feeds]]
id  = "1790944324"
url = "https://rss.art19.com/scam-factory"

[[feeds]]
id  = "1817249746"
url = "https://rss.art19.com/lawless-planet"

[[feeds]]
id  = "1726465829"
url = "https://rss.art19.com/the-rise-and-fall-of-ruby-franke"

[[feeds]]
id  = "1769072368"
url = "https://rss.art19.com/kill-list"

[[feeds]]
id  = "1480055524"
url = "https://rss.art19.com/the-mysterious-mr-epstein"

[[feeds]]
id  = "1500477470"
url = "https://rss.art19.com/even-the-rich"

[[feeds]]
id  = "1838792683"
url = "https://rss.art19.com/chasing-ghislaine"

[[feeds]]
id  = "1546027998"
url = "https://rss.art19.com/business-movers"

[[feeds]]
id  = "1701817343"
url = "https://rss.art19.com/the-big-flop"

[[feeds]]
id  = "1839479557"
url = "https://rss.art19.com/fbi-profilers"

[[feeds]]
id  = "1772686997"
url = "https://rss.art19.com/the-best-idea-yet"

[[feeds]]
id  = "1753789609"
url = "https://rss.art19.com/hysterical"

[[feeds]]
id  = "1756594491"
url = "https://rss.art19.com/karen"

[[feeds]]
id  = "1704893895"
url = "https://rss.art19.com/-exposed-"

[[feeds]]
id  = "1370096738"
url = "https://rss.art19.com/the-wonderland-murders"

[[feeds]]
id  = "1141563910"
url = "https://rss.art19.com/the-fall-of-rome-podcast"

[[feeds]]
id  = "1580881826"
url = "https://rss.art19.com/suspect"

[[feeds]]
id  = "1709404690"
url = "https://rss.art19.com/severed-affair"

[[feeds]]
id  = "1715319542"
url = "https://feeds.megaphone.fm/firecrackerpodcast"

[[feeds]]
id  = "1618471287"
url = "https://rss.art19.com/will-be-wild"

[[feeds]]
id  = "1852032918"
url = "https://rss.art19.com/heat-list"

[[feeds]]
id  = "1467256065"
url = "https://rss.art19.com/1865"

[[feeds]]
id  = "1623883114"
url = "https://rss.art19.com/the-disturbing-truth"

[[feeds]]
id  = "1667678268"
url = "https://rss.art19.com/devil-in-the-dorm"

[[feeds]]
id  = "1537865727"
url = "https://rss.art19.com/do-no-harm"

[[feeds]]
id  = "1713953535"
url = "https://rss.art19.com/crime-fix"

[[feeds]]
id  = "1658887127"
url = "https://feeds.acast.com/public/shows/675a40bd42ff44cc4d755761"

[[feeds]]
id  = "1780643357"
url = "https://rss.art19.com/the-rise-and-fall-of-diddy"

[[feeds]]
id  = "1482851200"
url = "https://rss.art19.com/bad-batch"

[[feeds]]
id  = "1743266064"
url = "https://rss.art19.com/happily-never-after-dan-and-nancy"

[[feeds]]
id  = "1835015455"
url = "https://rss.art19.com/moms-car"

[[feeds]]
id  = "1771526596"
url = "https://rss.art19.com/black-swan-murder"

[[feeds]]
id  = "1692238236"
url = "https://rss.art19.com/think-twice-michael-jackson"

[[feeds]]
id  = "1545233696"
url = "https://rss.art19.com/apology-line"

[[feeds]]
id  = "1739807599"
url = "https://rss.art19.com/the-price-of-paradise"

[[feeds]]
id  = "1797632117"
url = "https://rss.art19.com/luigi"

[[feeds]]
id  = "1807341101"
url = "https://rss.art19.com/death-county-pa"

[[feeds]]
id  = "1609466357"
url = "https://rss.art19.com/twin-flames"

[[feeds]]
id  = "1182568087"
url = "https://rss.art19.com/hollywood-and-crime-wondery"

[[feeds]]
id  = "1705431974"
url = "https://rss.art19.com/hooked-on-freddie"

[[feeds]]
id  = "1467123067"
url = "https://rss.art19.com/confronting-oj-simpson"

[[feeds]]
id  = "1370092284"
url = "https://rss.art19.com/american-innovations-podcast"

[[feeds]]
id  = "1581684171"
url = "https://rss.art19.com/9-12"

[[feeds]]
id  = "1790456066"
url = "https://rss.art19.com/we-came-to-the-forest"

[[feeds]]
id  = "1770164802"
url = "https://rss.art19.com/informants-lawyer-x"

[[feeds]]
id  = "1770789362"
url = "https://rss.art19.com/criminal-lives"

[[feeds]]
id  = "1766793973"
url = "https://rss.art19.com/criminal-attorney"

[[feeds]]
id  = "1656128059"
url = "https://rss.art19.com/frozen-head"

[[feeds]]
id  = "1751330154"
url = "https://rss.art19.com/empire-city"

[[feeds]]
id  = "1689293065"
url = "https://rss.art19.com/diss-and-tell"

[[feeds]]
id  = "1778080396"
url = "https://rss.art19.com/fire-escape"

[[feeds]]
id  = "1594927287"
url = "https://rss.art19.com/harsh-reality-the-story-of-miriam-rivera"

[[feeds]]
id  = "1726451032"
url = "https://rss.art19.com/black-history-for-real"

[[feeds]]
id  = "1437935588"
url = "https://rss.art19.com/gladiator-aaron-hernandez-and-football-inc"

[[feeds]]
id  = "1744021401"
url = "https://rss.art19.com/sins-of-the-child"

[[feeds]]
id  = "1625387454"
url = "https://rss.art19.com/the-french-deception"

[[feeds]]
id  = "1561686270"
url = "https://rss.art19.com/in-god-we-lust"

[[feeds]]
id  = "1557382427"
url = "https://rss.art19.com/spy-affair"

[[feeds]]
id  = "1484142154"
url = "https://rss.art19.com/blood-ties"

[[feeds]]
id  = "1459899327"
url = "https://rss.art19.com/life-is-short-with-justin-long"

[[feeds]]
id  = "1591623323"
url = "https://rss.art19.com/operator"

[[feeds]]
id  = "1628833551"
url = "https://feed.cdnstream1.com/zjb/feed/download/58/b2/63/58b263b5-bc0b-4aaf-b550-836b3a230a63.xml"

[[feeds]]
id  = "1611836389"
url = "https://rss.art19.com/call-me-curious"

[[feeds]]
id  = "1439810326"
url = "https://rss.art19.com/imagined-life"

[[feeds]]
id  = "1694361829"
url = "https://rss.art19.com/academy"

[[feeds]]
id  = "1633479565"
url = "https://rss.art19.com/fedup"

[[feeds]]
id  = "1664903728"
url = "https://rss.art19.com/stolen-hearts"

[[feeds]]
id  = "1706397719"
url = "https://rss.art19.com/i-hear-fear"

[[feeds]]
id  = "1621360648"
url = "https://rss.art19.com/daphne"

[[feeds]]
id  = "1252155965"
url = "https://rss.art19.com/locked-up-abroad"

[[feeds]]
id  = "1825461059"
url = "https://rss.art19.com/nick-cannon-at-night"

[[feeds]]
id  = "1387670973"
url = "https://rss.art19.com/inside-jaws"

[[feeds]]
id  = "1207876943"
url = "https://rss.art19.com/inside-psycho-wondery"

[[feeds]]
id  = "1562884524"
url = "https://rss.art19.com/the-vaping-fix"

[[feeds]]
id  = "1458930048"
url = "https://rss.art19.com/sports-wars"

[[feeds]]
id  = "1494781373"
url = "https://rss.art19.com/wecrashed"

[[feeds]]
id  = "1441566326"
url = "https://rss.art19.com/the-dan-abrams-pod"

[[feeds]]
id  = "1695950765"
url = "https://rss.art19.com/murder-on-my-mind"

[[feeds]]
id  = "1703838739"
url = "https://rss.art19.com/we-playin-spades"

[[feeds]]
id  = "1436752562"
url = "https://rss.art19.com/legal-wars"

[[feeds]]
id  = "1755411802"
url = "https://wondery.com/?rss_id=15994&rss_key=1798&rss_mixer"

[[feeds]]
id  = "1526747332"
url = "https://rss.art19.com/bunga-bunga"

[[feeds]]
id  = "1501568556"
url = "https://rss.art19.com/joe-exotic"

[[feeds]]
id  = "1732327043"
url = "https://rss.art19.com/the-last-city"

[[feeds]]
id  = "1685258534"
url = "https://rss.art19.com/spellcaster"

[[feeds]]
id  = "1849241057"
url = "https://rss.art19.com/here-is-unusual-suspects"

[[feeds]]
id  = "1728930866"
url = "https://rss.art19.com/blame-it-on-the-fame-mv"

[[feeds]]
id  = "1272973183"
url = "https://rss.art19.com/inside-the-exorcist"

[[feeds]]
id  = "1589218971"
url = "https://rss.art19.com/uncommon-ground-with-van-jones"

[[feeds]]
id  = "1572332094"
url = "https://rss.art19.com/100-percent-with-marcus-lemonis"

[[feeds]]
id  = "1708275587"
url = "https://rss.art19.com/class-of-88"

[[feeds]]
id  = "1701854906"
url = "https://rss.art19.com/alternate_feeds/user/killer-psyche-daily/ognrwzrBK7K8JFtR3E0kH5iKNAu-iMJl"

[[feeds]]
id  = "1560843836"
url = "https://rss.art19.com/secret-sauce"

[[feeds]]
id  = "1459899343"
url = "https://rss.art19.com/inside-star-wars"

[[feeds]]
id  = "1405751724"
url = "https://rss.art19.com/i-survivor"

[[feeds]]
id  = "1411446648"
url = "https://rss.art19.com/business-wars-daily"

[[feeds]]
id  = "1511191961"
url = "https://rss.art19.com/the-daily-smile"

[[feeds]]
id  = "1532496557"
url = "https://rss.art19.com/kamala-next-in-line"

[[feeds]]
id  = "1576881202"
url = "https://rss.art19.com/true-love"

[[feeds]]
id  = "1739595713"
url = "https://rss.art19.com/the-competition"

[[feeds]]
id  = "1148704291"
url = "https://rss.art19.com/i-hate-my-boss-wondery"

[[feeds]]
id  = "1175563320"
url = "https://rss.art19.com/terms-wondery"

[[feeds]]
id  = "1688764014"
url = "https://rss.art19.com/i-love-my-kid-but"

[[feeds]]
id  = "1530065734"
url = "https://rss.art19.com/say-yes-with-carla-hall"

[[feeds]]
id  = "1592641611"
url = "https://rss.art19.com/country-heat-weekly"

[[feeds]]
id  = "1128237784"
url = "https://rss.art19.com/found-wondery"

[[feeds]]
id  = "1471166224"
url = "https://rss.art19.com/the-moment"

[[feeds]]
id  = "1700746436"
url = "https://rss.art19.com/sports-world-explained"

[[feeds]]
id  = "1574595962"
url = "https://rss.art19.com/meditation"

[[feeds]]
id  = "1534643713"
url = "https://rss.art19.com/the-chicago-7"

[[feeds]]
id  = "1682546115"
url = "https://rss.art19.com/flipping-the-bird-elon-vs-twitter"

[[feeds]]
id  = "1649210117"
url = "https://feeds.megaphone.fm/beneath"

[[feeds]]
id  = "1623828594"
url = "https://rss.art19.com/queen-of-hearts"

[[feeds]]
id  = "1583090864"
url = "https://rss.art19.com/celeb-vs-superfan"

[[feeds]]
id  = "1773271613"
url = "https://rss.art19.com/rivals-the-official-pod"

[[feeds]]
id  = "1677383740"
url = "https://rss.art19.com/rotation-roundtable"

[[feeds]]
id  = "1535879416"
url = "https://rss.art19.com/jacked"

[[feeds]]
id  = "1353460577"
url = "https://rss.art19.com/safe-for-work"

[[feeds]]
id  = "1478448344"
url = "https://rss.art19.com/the-lead"

[[feeds]]
id  = "1319436103"
url = "https://rss.art19.com/launch"

[[feeds]]
id  = "1574583087"
url = "https://rss.art19.com/imagined-sleep"

[[feeds]]
id  = "1651866474"
url = "https://rss.art19.com/potato"

[[feeds]]
id  = "1248957387"
url = "https://rss.art19.com/heritage-road"

[[feeds]]
id  = "1449642919"
url = "https://rss.art19.com/one-plus-one"

[[feeds]]
id  = "1638819765"
url = "https://rss.art19.com/tepito-barrio-brava"

[[feeds]]
id  = "1148704289"
url = "https://rss.art19.com/secrets-crimes-audiotape-wondery"

[[feeds]]
id  = "1441570467"
url = "https://rss.art19.com/people-like-us"

[[feeds]]
id  = "1503721630"
url = "https://rss.art19.com/fighting-coronavirus-from-american-innovations"

[[feeds]]
id  = "1624552759"
url = "https://rss.art19.com/the-lead-starting-5"

[[feeds]]
id  = "1750702723"
url = "https://rss.art19.com/milli-vanilli"

[[feeds]]
id  = "1657131286"
url = "https://rss.art19.com/built-to-thrive"

[[feeds]]
id  = "1651727916"
url = "https://rss.art19.com/don-t-call-it-a-comeback"

[[feeds]]
id  = "1580797263"
url = "https://rss.art19.com/dr-death-hindi"
